FROM postgres:17-alpine
RUN mkdir -p /docker-entrypoint-initdb.d
COPY ddl/databasePGSQL.sql /tmp/init.sql
RUN cp /tmp/init.sql /docker-entrypoint-initdb.d/init.sql && \
    chmod 777 /docker-entrypoint-initdb.d/init.sql